# E-commerce docker compose

# backend on folder backend with Dockerfile
# frontend on folder frontend with Dockerfile

version: '3.7'

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_ECOMMERCE_API=http://localhost:8000
    ports:
      - 80:80
